Online-Store-CS-360-LUMS/config/routes.rb
Rails.application.routes.draw do
  

  resources :requests
  get 'purchases/report' => 'purchases#report'
  resources :purchases
  get 'sales/report' => 'sales#report'
  resources :sales
  resources :customers
  resources :orders
  resources :books
  
  
  root 'home#index'
  get 'login'=> 'sessions#new'
  

  resources :home
  
  get 'signup'  => 'admins#new' 
  resources :admins
  get 'login'=> 'sessions#new'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
  resources :sessions
  

end

Online-Store-CS-360-LUMS/app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  # before_action :require_admin, only: [:index]
  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:author, :edition, :bookTitle, :instructor, :courseCode)
    end
end

Online-Store-CS-360-LUMS/app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :edition %><br>
    <%= f.text_field :edition %>
  </div>
  <div class="field">
    <%= f.label :bookTitle %><br>
    <%= f.text_field :bookTitle %>
  </div>
  <div class="field">
    <%= f.label :instructor %><br>
    <%= f.text_field :instructor %>
  </div>
  <div class="field">
    <%= f.label :courseCode %><br>
    <%= f.text_field :courseCode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Online-Store-CS-360-LUMS/app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

Online-Store-CS-360-LUMS/app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Requests</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Edition</th>
      <th>Booktitle</th>
      <th>Instructor</th>
      <th>Coursecode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.author %></td>
        <td><%= request.edition %></td>
        <td><%= request.bookTitle %></td>
        <td><%= request.instructor %></td>
        <td><%= request.courseCode %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

Online-Store-CS-360-LUMS/app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

Online-Store-CS-360-LUMS/app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @request.author %>
</p>

<p>
  <strong>Edition:</strong>
  <%= @request.edition %>
</p>

<p>
  <strong>Booktitle:</strong>
  <%= @request.bookTitle %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @request.instructor %>
</p>

<p>
  <strong>Coursecode:</strong>
  <%= @request.courseCode %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>