config/routes.rb
Rails.application.routes.draw do
  

  resources :requests
  get 'purchases/report' => 'purchases#report'
  resources :purchases
  get 'sales/report' => 'sales#report'
  get 'sales/return' => 'sales#returnS'
  resources :sales
  resources :customers
  get 'orders/return' => 'orders#returnB'
  resources :orders
  resources :books
  
  
  root 'home#index'
  get 'login'=> 'sessions#new'
  

  resources :home
  get 'orders/new/:id' => 'orders#new'
  get 'signup'  => 'admins#new' 
  resources :admins
  get 'admin'=> 'sessions#new'
  post 'login' => 'sessions#create'
  post 'orders/create' => 'orders#create'
  post 'sales/create' => 'sales#create'
  post 'purchases/create' => 'purchases#create'
  delete 'logout' => 'sessions#destroy'
  get'logout' => 'sessions#destroy'
  resources :sessions
  
  post 'tracker' => 'orders#tracker'
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
    has_secure_password
    # Returns the hash digest of the given string.

    
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :courseTitle, presence: true
    def self.search(search)
      if search
        where("courseTitle LIKE ?", "%#{search}%")
      else
        Book.all
      end
    end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/sale.rb
class Sale < ActiveRecord::Base
    All_ratings = ['G','PG','PG-13','R','NC-17'] 
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  
  before_action :require_admin, only: [:index]
  
  def index
  end
  
    def new
    @admin = Admin.new
    end
    
    def create 
  @admin = Admin.new(admin_params) 
  if @admin.save! 
    session[:admin_id] = @admin.id 
    redirect_to '/admins' 
  else 
    redirect_to '/signup' 
   end 
  end
    
    
      def admin_params
    params.require(:admin).permit(:first_name, :last_name, :email, :password)
    end
  end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:new, :edit, :create, :update, :destroy]
  
  # GET /books
  # GET /books.json
  def index
    # @books = Book.all
    @books = Book.search(params[:search])
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if not @book.save
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
        else
          format.html { redirect_to @book, notice: 'Book was successfully created.' }
          format.json { render :show, status: :created, location: @book }
        
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:courseTitle, :courseCode, :instructor, :school, :ourPrice, :canotechPrice, :numCopies, :bookTitle, :author, :edition, :dept, :comment, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
    @home = Order.all
end
def new
end

def create
end

def destroy
end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  #before_action :require_admin, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  @selectedRatings = []
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

def returnS
end
  # GET /sales/1
  # GET /sales/1.json
  def show
  end
  
  def report
      @sales = Sale.all
      @allBooks = []
      @sales.each do |sale|
        @allBooks.push(Book.find_by(sale.bookID))
      end
  end
  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  
  def create
   if  ((params[:myid]["courseCode"] == "" || params[:myid]["instructor"] == "") && params[:orderid] == "") 
     flash[:notice] = "Enter Course Code and Instructor OR Order ID"
    redirect_to new_sale_path
    return
  else
    if (params[:orderid] != "" && !Order.exists?(id: params[:orderid]))
      flash[:notice] = "Enter Valid Order ID"
    redirect_to new_sale_path
      return
    elsif (params[:orderid] != "")
      order = Order.find(params[:orderid])
      Sale.create({"orderID" => order.id, "customerID" => order.customerID, "bookID" => order.bookIDs})
    end
  end
  if (params[:myid]["courseCode"] != "")
    if (params[:myid]["courseCode"] != params[:myid]["instructor"])
      flash[:notice] = "Instructor and Course Does Not Match!"
    redirect_to new_sale_path
      return
    else 
      Sale.create({"bookID" => params[:myid]["courseCode"]})
    end
  end
   redirect_to sales_path
   return
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:customerID, :orderID, :bookID, :quantity, :discount)
    end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
 <!-- Page Content -->
    <!--<div class="container">-->
      
        
        
        <!-- Jumbotron Header -->
        <div class="row title-img">
            
            <header class="jumbotron hero-spacer title-img text-center">
                <h2 class= "white section-heading large text-center">Welcome To OnePoint</h2>
                <div class="col-lg-2">
                    </div>
                <div class="col-lg-8">
                    <p class="lead white">We aim to provide high quality low cost Books and coursepack to students of LUMS.</p>
                    <p><a class="btn btn-primary btn-large k" href='/orders/new'>Place your order now!</a>
                </div>
                <div class="col-lg-2">
                    </div>
                
                </p>
            </header>
            <div class="row m"></div>
                        <div class="row m"></div>

            <!--<img src="https://i.imgsafe.org/486af6d.jpg"  height=50% >-->
        </div>
        <div>
            
        </div>
        

        <!--<hr>-->
        
       
        <div class="row bg-light-gray mar">
            <div class="container">
              <div class="row">
                <div class="col-lg-12 text-center">
                  <h3 class="section-title contact-title text-center">Featured Books</h3>
                  <!--<h3 class="section-subheading text-muted">Largest Online Book Store</h3>-->
                  </div>
              </div>
            </div>
            <div class="container">
              <div class="row previews">
                <% Book.all.each do |book| %>
                <div class="col-lg-4 col-sm-6">
                  <div class="thumbnail">
                    <a href=<%= book_path(book) %> class="post-image-link">
                      <p><img src=<%= book.image %> class="img-responsive"></p>
                      <!---->
                    </a>
                    <div class="caption">
                      <h3><%= book.courseTitle %></h3>
                      <p><%= book.instructor %></p>
                      <a href=<%= book_path(book) %> class="btn btn-primary">Preview</a>
                    <a href=<%= new_order_path + "/" + book.id.to_s %> class="btn btn-default">Purchase</a>
                  </div>
                </div>
                </div>
                <% end %>
              </div>
        </div>
          </div>
        
        
         
        <!-- Contact Us Section -->
        
        <div class="row text-center blue2">
        <section class="contact-us-section section-padding" id="contact">
             <div class="container">
             <!-- Contact Us Section Title -->
            <h3 class="section-title contact-title text-center white">Contact Us</h3>
            
             
             <div class="col-md-6 col-md-offset-3 white">
                 <form action="/" id="contact-form" class="form-horizontal" role="form" method="post">
                     <div class="form-group">
                     <label for="name" class="col-lg-2 control-label">Name</label>
                         <div class="col-lg-10">
                             <input type="text" class="form-control required" id="form-name" name="form-name" placeholder="Alex" />
                         </div>
                     </div>
                     <div class="form-group">
                         <label for="email" class="col-lg-2 control-label">Email</label>
                         <div class="col-lg-10">
                             <input type="email" class="form-control required" id="form-email" name="form-email" placeholder="eg.alex@gmail.com" />
                         </div>
                     </div>
                     <div class="form-group">
                         <label for="tel" class="col-lg-2 control-label">Mobile</label>
                         <div class="col-lg-10">
                             <input type="tel" class="form-control" id="form-tel" name="form-tel" placeholder="eg.03xx-xxxxxxx">
                        </div>
                     </div>
                     <div class="form-group">
                         <label for="assunto" class="col-lg-2 control-label">Subject</label>
                         <div class="col-lg-10">
                           <input type="text" class="form-control required" id="form-subject" name="form-subject" placeholder="Subject" />
                         </div>
                     </div>
                     <div class="form-group">
                         <label for="mensagem" class="col-lg-2 control-label">Text</label>
                         <div class="col-lg-10">
                             <textarea class="form-control required" rows="3" id="form-message" name="form-message" placeholder="Message" /></textarea>
                         </div>
                     </div>
                     <div class="form-group">
                         <div class="col-lg-offset-2 col-lg-10">
                             <button type="submit" class="btn btn-default">Send Message</button>
                         </div>
                     </div>
                 </form>
             </div>
         </div>
     </section>
     </div>

        <!-- End Of Contact Us Section -->
        
        <!-- /.row -->

        <!-- Footer -->
        <div class="row ">
            <div class="col-lg-12">
                <p>Copyright &copy; SE Group, Spring 2016</p>
            </div>
        </div>

    <!--</div>-->
    <!-- /.container -->




    
<!--<%= link_to 'Available Books', books_path %> <hr>-->
<!--<%= link_to 'Place order', new_order_path %><hr>-->
<!--<%= link_to 'Request a book', new_request_path %><hr>-->



<style>
  .caption{
    text-align: center;
  }
  .btn-primary { 
    	background-color: #1abc9c !important;
	}
	#portfolio {
	  margin-top: 80px;
	}
	.previews{
	  margin-top: 50px;
	  margin-bottom: 100px;
	}
	.white{
	       color: white;
	       margin-top: 20px;
	}
	.red{
	    background-color: #18bc9c;
	}
	.blue{
	    background-color: #3498db;
	}
	.blue2{
	    		background-color:#3b5999
	}
	.noidea{
	    background-color: #e74c3c;
	}
	.green {
	    background-color: #2ecc71;
	}
	.title-img{
	    /*background-color: #2ecc71;*/
	    background-image: url("https://i.imgsafe.org/486af6d.jpg");
	}
	.mar{
	    margin-top: 30px;
	}
	.m{
	    margin-bottom: 150px;
	}
	.large{
	    font-size: 50px;
	}
	.k{
	    font-size: 18px;
	    color: white !important;
	}
	}
	
</style>

<script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>