config/routes.rb
Rails.application.routes.draw do
  

  resources :requests
  get 'purchases/report' => 'purchases#report'
  resources :purchases
  get 'sales/report' => 'sales#report'
  get 'sales/return' => 'sales#returnS'
  resources :sales
  resources :customers
  get 'orders/return' => 'orders#returnB'
  resources :orders
  resources :books
  
  
  root 'home#index'
  get 'login'=> 'sessions#new'
  

  resources :home
  get 'orders/new/:id' => 'orders#new'
  get 'signup'  => 'admins#new' 
  resources :admins
  get 'admin'=> 'sessions#new'
  post 'login' => 'sessions#create'
  post 'orders/create' => 'orders#create'
  post 'sales/create' => 'sales#create'
  post 'purchases/create' => 'purchases#create'
  delete 'logout' => 'sessions#destroy'
  get'logout' => 'sessions#destroy'
  resources :sessions
  
  post 'tracker' => 'orders#tracker'
  

end

app/models/sale.rb
class Sale < ActiveRecord::Base
    All_ratings = ['G','PG','PG-13','R','NC-17'] 
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  #before_action :require_admin, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  @selectedRatings = []
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

def returnS
end
  # GET /sales/1
  # GET /sales/1.json
  def show
  end
  
  def report
      @sales = Sale.all
      @allBooks = []
      @sales.each do |sale|
        @allBooks.push(Book.find_by(sale.bookID))
      end
  end
  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  
  def create
   if  ((params[:myid]["courseCode"] == "" || params[:myid]["instructor"] == "") && params[:orderid] == "") 
     flash[:notice] = "Enter Course Code and Instructor OR Order ID"
    redirect_to new_sale_path
    return
  else
    if (params[:orderid] != "" && !Order.exists?(id: params[:orderid]))
      flash[:notice] = "Enter Valid Order ID"
    redirect_to new_sale_path
      return
    elsif (params[:orderid] != "")
      order = Order.find(params[:orderid])
      Sale.create({"orderID" => order.id, "customerID" => order.customerID, "bookID" => order.bookIDs})
    end
  end
  if (params[:myid]["courseCode"] != "")
    if (params[:myid]["courseCode"] != params[:myid]["instructor"])
      flash[:notice] = "Instructor and Course Does Not Match!"
    redirect_to new_sale_path
      return
    else 
      Sale.create({"bookID" => params[:myid]["courseCode"]})
    end
  end
   redirect_to sales_path
   return
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:customerID, :orderID, :bookID, :quantity, :discount)
    end

end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for @sale, :html => { :class => "form-horizontal sale" } do |f| %>

  <% if @sale.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @sale.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :customerID, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :customerID, :class => 'form-control' %>
    </div>
    <%=f.error_span(:customerID) %>
  </div>
  <div class="form-group">
    <%= f.label :orderID, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :orderID, :class => 'form-control' %>
    </div>
    <%=f.error_span(:orderID) %>
  </div>
  <div class="form-group">
    <%= f.label :bookID, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :bookID, :class => 'form-control' %>
    </div>
    <%=f.error_span(:bookID) %>
  </div>
  <div class="form-group">
    <%= f.label :quantity, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :quantity, :class => 'form-control' %>
    </div>
    <%=f.error_span(:quantity) %>
  </div>
  <div class="form-group">
    <%= f.label :discount, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :discount, :class => 'form-control' %>
    </div>
    <%=f.error_span(:discount) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Create Sale", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sales_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/sales/_sellform.html.erb
<div style = "text-align:center; color:red; font-size:15px">
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>
</div>

  <div  class="col-xs-5" style="margin-left: -1.5%;">
    <%= form_tag("/sales/create", method: "post") do %>

      <div class="form-group">  
        <%= label_tag :bookid, "Course Code" %>
        <%=  collection_select :myid,:courseCode, Book.all, :id, :courseCode, include_blank: true %>
     
      </div>
      
      <div class="form-group">  
        <%= label_tag :bookid, "Instructor" %>
        <%=  collection_select :myid,:instructor, Book.all, :id, :instructor, include_blank: true %>
     
      </div>
      <p style = "font-size:15px; font-weight:bold; text-align:center"> OR </p>
      <div class="form-group">
        <%= label_tag :orderid, "Order ID" %>
        <%= text_field_tag :orderid, nil, class: "form-control" %>
      </div>
      
      
      <%= submit_tag "Submit", class: "btn btn-default" %>
    <% end %>
  </div>

app/views/sales/edit.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/index.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:customerID) %></th>
      <th><%= model_class.human_attribute_name(:orderID) %></th>
      <th><%= model_class.human_attribute_name(:bookID) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:discount) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= link_to sale.id, sale_path(sale) %></td>
        <td><%= sale.customerID %></td>
        <td><%= sale.orderID %></td>
        <td><%= sale.bookID %></td>
        <td><%= sale.quantity %></td>
        <td><%= sale.discount %></td>
        <td><%=l sale.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      sale_path(sale),
                      :method => :get,
                      :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sale_path(sale), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sale_path(sale),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sale_path,
            :class => 'btn btn-primary' %>

app/views/sales/new.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%=  render :partial => 'sellform' %>

app/views/sales/report.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => 'Sales - Report' %></h1>
</div>

<%= check_box_tag "ratings[]"   %>

  
<table class="table table-striped">
  <thead>
    <tr>
      <th>Course Name</th>
      <th>Course Code</th>
      <th>Instructor</th>
      <th>Book title</th>
      <th>Quantity</th>
      <th>Revenue</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @allBooks.zip(@sales).each do |book, sale| %>
      <tr>
        <td><%= book.courseCode %></td>
        <td><%= book.courseTitle %></td>
        <td><%= book.instructor %></td>
        <td><%= book.bookTitle %></td>
        <td><%= sale.quantity %></td>
        <td><%= (sale.quantity*book.ourPrice)-sale.discount%></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sale_path(sale), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sale_path(sale),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sale_path,
            :class => 'btn btn-primary' %>

app/views/sales/show.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:customerID) %>:</strong></dt>
  <dd><%= @sale.customerID %></dd>
  <dt><strong><%= model_class.human_attribute_name(:orderID) %>:</strong></dt>
  <dd><%= @sale.orderID %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bookID) %>:</strong></dt>
  <dd><%= @sale.bookID %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @sale.quantity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:discount) %>:</strong></dt>
  <dd><%= @sale.discount %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              sales_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sale_path(@sale), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sale_path(@sale),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>